export const reasons = [
  "You make the miles between us feel absolutely meaningless.",
  "Hearing your voice on the phone is the best part of my entire day.",
  "I love how we can fall asleep together on a video call, even from far away.",
  "The way my heart races every single time I see your name light up my phone screen.",
  "You always find creative, sweet ways to make me feel loved from a distance.",
  "Counting down the days until I see you gives me the best kind of butterflies.",
  "That indescribable feeling of finally getting to hug you tightly at the airport or station.",
  "I love that this distance has only forced us to build a stronger emotional connection.",
  "You send the most adorable good morning texts that start my day perfectly.",
  "Our virtual movie dates are just as fun as being in a real theater together.",

  "You trust me completely, and that makes me feel incredibly safe.",
  "The thrill of opening a surprise package or ordering food for each other from miles away.",
  "You always make time for our calls, no matter how busy your day gets.",
  "I love keeping your hoodies and wearing them when I missing your scent.",
  "You listen to my voice notes with so much attention and care.",
  "The way we can be completely silent on the phone and still feel totally connected.",
  "You know exactly how to comfort me through a screen when I've had a bad day.",
  "I love how we share our daily routines like we're right there with each other.",
  "You validate my feelings when the distance gets hard and I just miss you.",
  "The way you look at the camera when we're on FaceTime makes me melt.",

  "Every time we say goodbye, you assure me that the next hello will be worth it.",
  "I love waking up to paragraphs of text from you explaining how much you love me.",
  "You never let me go to sleep feeling unloved or uncertain.",
  "The way we plan our future together makes every difficult day completely worth it.",
  "You make our digital dates feel like incredible romantic adventures.",
  "I love looking at photos of you when I miss your face.",
  "You send me the funniest reels and memes that perfectly match my humor.",
  "I love how we can just leave the video call running while we do our own things.",
  "You are so patient when the wifi lags or the call drops.",
  "The way you randomly text me 'I miss you' right when I'm thinking the same thing.",

  "I love creating shared playlists that we can listen to at the exact same time.",
  "You always tell me about the small details of your day so I feel included.",
  "The excitement of planning our next trip to finally see each other.",
  "I love how we have our own little language over text.",
  "You never make me feel crazy for needing extra reassurance when we're apart.",
  "The warmth I feel when I look at the countdown app on my phone.",
  "You manage to make me laugh until my stomach hurts, even through a speaker.",
  "I love the screenshots you take of me when I look 'cute' on FaceTime.",
  "You are my absolute favorite notification.",
  "The way you handle the time difference like it's no big deal.",

  "I love falling asleep knowing we are looking at the same moon.",
  "You always remember the little things I mentioned in passing two weeks ago.",
  "The way your sleepy voice sounds on the phone late at night.",
  "I love how deeply we've learned to communicate our needs from a distance.",
  "You are the perfect excuse to spend hours on my phone.",
  "The way you support my goals, even if it means we have to stay apart a little longer.",
  "I love seeing your face light up when I show you something new in my room.",
  "You make me feel like I am the only person in the world, even from across the map.",
  "The way we hype each other up before big meetings or exams over text.",
  "I love that we've built a relationship on pure trust and genuine connection.",

  "You never let the miles turn into emotional distance.",
  "The way you say my name through the phone makes me instantly smile.",
  "I love how we can have dinner 'together' over a screen and just vibe.",
  "You send me pictures of things that reminded you of me during your day.",
  "The overwhelming joy of waking up knowing it's the day I finally get to travel to you.",
  "I love that nothing feels awkward when we finally meet up, we just pick up right where we left off.",
  "You are constantly finding new online games or quizzes for us to do together.",
  "The way you tell me you wish you could hug me when I'm feeling down.",
  "I love that you are worth every single mile, train ride, and plane ticket.",
  "You always check to make sure I got home safe, no matter where I am.",

  "The way you make our long distance feel like a beautiful love story.",
  "I love how our relationship proves that true love has no physical boundaries.",
  "You give me the strength to be independent while still being completely yours.",
  "The way we celebrate tiny milestones, like being one week closer to seeing each other.",
  "I love keeping the little souvenirs from our visits as treasures.",
  "You always find a way to make your presence felt when I really need you.",
  "The way you listen to me complain about the distance but still keep me positive.",
  "I love that we are building an unbreakable foundation for our future.",
  "You are constantly reminding me of how beautiful I am, even when I feel like a mess on camera.",
  "The way my heart does a little flip when you accidentally call me instead of texting.",

  "I love how we can just text emojis and know exactly what the other means.",
  "You never let our spark fade, no matter how long it's been since we last hugged.",
  "The comforting thought that every day apart is one day closer to being together forever.",
  "I love the intense eye contact we maintain even through a phone screen.",
  "You are my literal favorite hello and my hardest goodbye.",
  "The way you make a simple 'goodnight' text feel so warm and meaningful.",
  "I love that our love relies on our hearts and minds, not just physical touch.",
  "You always try to align your schedule with mine just so we get to talk a bit longer.",
  "The way you make the waiting feel beautiful instead of painful.",
  "I love how you always manage to be the first person to wish me a happy birthday at midnight.",

  "You make checking my mail exciting because of your surprise letters and gifts.",
  "The way you reassure me that the distance is only temporary.",
  "I love how we can just sit and dream about our future apartment together.",
  "You are so good at reading my mood just from the tone of my text messages.",
  "The way you tell me about the food you're eating so I feel like I'm tasting it too.",
  "I love the feeling of finally taking a nap together in person after months of virtual sleep.",
  "You make my heart smile every single day without fail.",
  "The way you show off my picture to your friends even when I'm not there.",
  "I love our late-night existential talks when the rest of the world is asleep.",
  "You always appreciate the effort I put into visiting you or staying up late.",

  "The way you make every single second of our visits absolutely magical.",
  "I love that we cherish our time together so much more than normal couples.",
  "You are proof that distance means so little when someone means so much.",
  "The way you hold onto me so tightly when we finally reunite.",
  "I love the undeniable chemistry we have, even from miles away.",
  "You make me feel incredibly valued, treasured, and prioritized from afar.",
  "The way you never give up on us, even when the distance feels overwhelming.",
  "I love that we are writing the most unique and beautiful love story together.",
  "You make me look forward to every single tomorrow because I'm closer to you.",
  "I love you, simply because no amount of distance could ever change how I feel about you."
];
